In [18]:
import numpy as np

v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
v3 = np.array([7, 8, 9, 10])

v12 = v1.dot(v2)

print(v12)
print(v1 @ v2)

v13 = np.multiply(v1, v2)  # This will raise an error because the shapes are not aligned
print(v13)

# Broadcasting: arreglo 1D con un escalar
a = np.array([1, 2, 3])
b = 5

# El escalar se transmite a todo el arreglo
broadcasting_result = a + b
print("Resultado de Broadcasting:", broadcasting_result)

32
32
[ 4 10 18]
Resultado de Broadcasting: [6 7 8]


In [ ]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print("Matriz original:\n", matriz)
matriz = matriz.ravel()
print("Matriz aplanada:", matriz)

In [23]:
v1= np.array([1, 2, 3], dtype=np.int32)
v2= np.array([4, 5, 6], dtype=np.int32)

v3 = v1.sum()
print("Suma de v1:", v3)

Suma de v1: 6


In [29]:
# Valore estadisticos
v1 = np.array([1, 2, 3, 4, 5])
v2 = np.array([[5, 6, 7],[8, 9, 10]])
print(f"v1: {v1}")
print(f"v2: {v2}")

print(f"Media de v1: {v1.mean()}")
print(f"Desviación estándar de v1: {v1.std()}")
print(f"Varianza de v1: {v1.var()}")
print(f"Máximo de v1: {v1.max()}")
print(f"Mínimo de v1: {v1.min()}")
print(f"Mediana de v1: {np.median(v1)}")
print(f"Cuartiles de v1: {np.percentile(v1, [25, 50, 75])}")
print(f"Cuartiles de v2: {np.percentile(v2, [25, 50, 75])}")

#ordenar valores
v1 = np.array([3, 1, 4, 2])
v2 = np.array([5, 3, 2, 4])
print(f"v1: {v1}")
print(f"v2: {v2}")
print(f"v1 ordenado: {np.sort(v1)}")
print(f"v2 ordenado: {np.sort(v2)}")

#ordenar por filas
v1 = np.array([[3, 1, 4], [2, 5, 3]])
v2 = np.array([[5, 3, 2], [4, 1, 6]])
print(f"v1:\n{v1}")
print(f"v2:\n{v2}")
print(f"v1 ordenado por filas:\n{np.sort(v1, axis=1)}")
print(f"v2 ordenado por filas:\n{np.sort(v2, axis=1)}")



v1: [1 2 3 4 5]
v2: [[ 5  6  7]
 [ 8  9 10]]
Media de v1: 3.0
Desviación estándar de v1: 1.4142135623730951
Varianza de v1: 2.0
Máximo de v1: 5
Mínimo de v1: 1
Mediana de v1: 3.0
Cuartiles de v1: [2. 3. 4.]
Cuartiles de v2: [6.25 7.5  8.75]
v1: [3 1 4 2]
v2: [5 3 2 4]
v1 ordenado: [1 2 3 4]
v2 ordenado: [2 3 4 5]
v1:
[[3 1 4]
 [2 5 3]]
v2:
[[5 3 2]
 [4 1 6]]
v1 ordenado por filas:
[[1 3 4]
 [2 3 5]]
v2 ordenado por filas:
[[2 3 5]
 [1 4 6]]


In [28]:
#ordenar por columnas
v1 = np.array([[3, 1, 4], [2, 5, 3]])
v2 = np.array([[5, 3, 2], [4, 1, 6]])
print(f"v1:\n{v1}")
print(f"v2:\n{v2}")
print(f"v1 ordenado por columnas:\n{np.sort(v1, axis=0)}")
print(f"v2 ordenado por columnas:\n{np.sort(v2, axis=0)}")

v1:
[[3 1 4]
 [2 5 3]]
v2:
[[5 3 2]
 [4 1 6]]
v1 ordenado por columnas:
[[2 1 3]
 [3 5 4]]
v2 ordenado por columnas:
[[4 1 2]
 [5 3 6]]
